// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createOfflineQueryBuilder() {
  const state: { proxy?: any } = {};

  const builder = {
    select: () => state.proxy,
    eq: () => state.proxy,
    order: () => state.proxy,
    limit: () => state.proxy,
    gte: () => state.proxy,
    lte: () => state.proxy,
    gt: () => state.proxy,
    lt: () => state.proxy,
    ilike: () => state.proxy,
    in: () => state.proxy,
    contains: () => state.proxy,
    or: () => state.proxy,
    match: () => state.proxy,
    maybeSingle: async () => ({ data: null, error: null }),
    single: async () => ({ data: null, error: null }),
    insert: async () => ({ data: null, error: { message: "Supabase is disabled in offline mode" } }),
    update: async () => ({ data: null, error: { message: "Supabase is disabled in offline mode" } }),
    upsert: async () => ({ data: null, error: { message: "Supabase is disabled in offline mode" } }),
    delete: async () => ({ data: null, error: { message: "Supabase is disabled in offline mode" } }),
    then: (onFulfilled: (value: { data: never[]; error: null; count: number }) => unknown, onRejected?: (reason: unknown) => unknown) =>
      Promise.resolve({ data: [], error: null, count: 0 }).then(onFulfilled, onRejected),
    catch: (onRejected: (reason: unknown) => unknown) => Promise.resolve({ data: [], error: null, count: 0 }).catch(onRejected),
    finally: (onFinally: () => void) => Promise.resolve({ data: [], error: null, count: 0 }).finally(onFinally),
  };

  state.proxy = new Proxy(builder, {
    get(target, prop) {
      if (prop in target) return Reflect.get(target, prop);
      return () => state.proxy;
    },
  });

  return state.proxy;
}

function createOfflineChannel() {
  const channel: any = {
    on: () => channel,
    subscribe: () => channel,
    unsubscribe: () => undefined,
  };
  return channel;
}

function createOfflineSupabaseClient() {
  const offlineQuery = createOfflineQueryBuilder();

  return {
    auth: {
      onAuthStateChange: () => ({
        data: {
          subscription: { unsubscribe: () => undefined },
        },
      }),
      getSession: async () => ({ data: { session: null }, error: null }),
      getClaims: async () => ({ data: null, error: { message: "Supabase is disabled in offline mode" } }),
      signInWithOtp: async () => ({
        data: { user: null, session: null },
        error: { message: "Supabase is disabled in offline mode" },
      }),
      verifyOtp: async () => ({
        data: { user: null, session: null },
        error: { message: "Supabase is disabled in offline mode" },
      }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: { message: "Supabase is disabled in offline mode" },
      }),
      signOut: async () => ({ data: null, error: null }),
    },
    from: () => offlineQuery,
    channel: () => createOfflineChannel(),
    removeChannel: () => undefined,
  } as unknown as ReturnType<typeof createSupabaseClient>;
}

function createSupabaseClient() {
  const processEnv = typeof process !== "undefined" ? process.env : {};
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    import.meta.env.NEXT_PUBLIC_SUPABASE_URL ||
    processEnv.SUPABASE_URL ||
    processEnv.NEXT_PUBLIC_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
    import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
    processEnv.SUPABASE_ANON_KEY ||
    processEnv.SUPABASE_PUBLISHABLE_KEY ||
    processEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
    processEnv.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn("[Supabase] Missing env vars; using offline mock client.");
    return createOfflineSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
